import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
// custom providers
import { AuthProvider } from "@/context/authcontext";

const hoverFX = "hover:text-sky-300 duration-200 ease-in-out";
const linkstyle = "border rounded py-2.5"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Interntrack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* navbar for all pages */}
        <nav className="text-xl h-[8.5vh] sticky top-0 z-50 p-3.5 space-x-7.5 flex flex-row">
          <Link href={`/`} className={hoverFX + linkstyle}>
            Home
          </Link>
          <Link href={`/login`} className={hoverFX + linkstyle}>
            Login
          </Link>
          <Link href={`/signup`} className={hoverFX + linkstyle}>
            Signup
          </Link>
          <Link href={`/`} className={hoverFX + linkstyle}>
            Suggestions
          </Link>
          <h1 className="text-4xl font-bold">InternTrack</h1>
        </nav>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
